# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mr. Malty iOS Yeast Calculator App
email: noah.paci@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yeast calculator app uses Mr. Malty's emperically determined yeast calculations to generate target populations for 
  home brewing and professional brewing.  Works for any volume, scale, or strength of beer.'.
baseurl: "/jekyll_test" # the subpath of your site, e.g. /blog
url: "http://np0x.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
# github_username:  np0x

# Build settings
markdown: kramdown
